service: stream-processing

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline
  - serverless-mocha-plugin

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
